package com.aluracursos.modelos;

public enum Menu {
    CONVERTIR_DOLAR_A_PESO_ARGENTINO,
    CONVERTIR_PESO_ARGENTINO_A_DOLAR,
    CONVERTIR_DOLAR_A_REAL_BRASILERO,
    CONVERTIR_REAL_BRASILERO_A_DOLAR,
    CONVERTIR_DOLAR_A_PESO_COLOMBIANO,
    CONVERTIR_PESO_COLOMBIANO_A_DOLAR,
    SALIR

}
